networks:
  saas_network:
    driver: ${NETWORKS_DRIVER}

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      DEFAULT_MYSQL_DATABASE: multi_tenant_saas
      DB_DATABASE_BILLING: ${BILLING_SERVICE_DATABASE}
      DB_DATABASE_NOTIFICATION: ${NOTIFICATION_SERVICE_DATABASE}
      DB_DATABASE_AUTH: ${AUTH_SERVICE_DATABASE}
      DB_DATABASE_API_SERVICE: ${SAAS_API_SERVICE_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh 
      - ./mysql/scripts:/scripts
    networks:
      - saas_network

  billify-saas:
    build:
      context: ./laravel-saas
      dockerfile: Dockerfile
    container_name: billing-service
    environment:
      APP_ENV: "local"
      APP_URL: http://billify-saas:80
    volumes:
      - ./projects/billify-saas:/var/www/app
      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - ./logs/nginx/billify-saas:/var/log/nginx/billify-saas
    networks:
      - saas_network
    depends_on:
      - mysql

  notifi-saas:
    build:
      context: ./laravel-saas
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      APP_ENV: "local"
      APP_URL: http://notifi-saas:80
    volumes:
      - ./projects/notifi-saas:/var/www/app
      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - ./logs/nginx/notifi-saas:/var/log/nginx/notifi-saas
    networks:
      - saas_network
    depends_on:
      - mysql

  autho-saas:
    build:
      context: ./laravel-saas
      dockerfile: Dockerfile
    container_name: authentication-service
    environment:
      APP_ENV: "local"
      APP_URL: http://autho-saas:80
    volumes:
      - ./projects/autho-saas:/var/www/app
      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - ./logs/nginx/autho-saas:/var/log/nginx/autho-saas
    networks:
      - saas_network
    depends_on:
      - mysql

  saas-api:
    build:
      context: ./laravel-saas
      dockerfile: Dockerfile
    container_name: api-middleware
    ports:
      - "${SAAS_API_SERVICE_APP_PORT}:80"
    environment:
      APP_ENV: "local"
      APP_URL: http://localhost:${SAAS_API_SERVICE_APP_PORT}
    volumes:
      - ./projects/saas-api-middleware:/var/www/app
      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - ./logs/nginx/saas-api-middleware:/var/log/nginx/saas-api-middleware
    networks:
      - saas_network
    depends_on:
      - mysql
      - billify-saas
      - notifi-saas
      - autho-saas
      - mailpit

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - saas_network

volumes:
  db_data: