-- Create the database (if it doesn't exist)
CREATE DATABASE IF NOT EXISTS ${DEFAULT_MYSQL_DATABASE};
CREATE DATABASE IF NOT EXISTS ${DB_DATABASE_BILLING};
CREATE DATABASE IF NOT EXISTS ${DB_DATABASE_NOTIFICATION};
CREATE DATABASE IF NOT EXISTS ${DB_DATABASE_AUTH};

-- Grant the necessary privileges to the user on the specific database
GRANT ALL PRIVILEGES ON ${DEFAULT_MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${DB_DATABASE_BILLING}.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${DB_DATABASE_NOTIFICATION}.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${DB_DATABASE_AUTH}.* TO '${MYSQL_USER}'@'%';

-- Apply the changes
FLUSH PRIVILEGES;